version: "3"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
        - './src:/var/www/html'
        - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
      image: mysql:5.7
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=docker-lamp
        - MYSQL_USER=user
        - MYSQL_PASSWORD=root

