<?php
/**
 * Просто какая-то обыкновенная модель с какими-то полями.
 *
 * @author Sarychev Aleksey <freddis336@gmail.com>
 */
class GenericModel extends AccessLog
{
        /**
     * Возвращает новую модель данного класса. 
     * Этот метод необязателен, но улучшает работу подсказок.
     * 
     * @autogenerated 27-10-2016
     * @param String $className Имя класса модели
     * @return Statistics пустой объект модели
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }
    
    public function tableName()
    {
        return "genericmodels";
    }
}
