<?php

/**
 * Модель пользователя проекта. Содержит уникальные для проекта функции.
 */
class User extends BaseUser
{

    public function __construct($scenario = 'insert')
    {
        parent::__construct($scenario);
    }

    /**
     *  Возвращает правила валидации.
     * <b>Внимание: для полей у которых в БД тип VARCHAR необходимо создать валидатор "length".</b>
     *
     * @autogenerated 29-08-2017
     * @return Array[] Массив правил валидации
     */
    public function rules()
    {
        $arr = parent::rules();
        $arr[] = array('email', 'required');
        return $arr;
    }

    /**
     * Возвращает массив связей моделей.
     * <b>Внимание: связи BELONGS_TO являются внешними ключами.</b> Для них можно указать поведение при удалений родительской сущности.
     *
     * @return Array[] Массив связей
     * @autogenerated 23-07-2017 Merged
     */
    public function relations()
    {
        $arr = parent::relations();
        return $arr;
    }
}
