<?php

/**
 * Модель для данных для статистики
 * 
 * @author Dudochkina Ekaterina <edudochkina@home-studio.pro>
 * @package Hs\Models
 */
class AccessLog extends ActiveRecord
{
    /**
     * Первичный ключ
     * 
     * @var Integer
     * @autogenerated 27-10-2016
     */
    public $id;

    /**
     * Ip пользователя
     * 
     * @var String
     * @autogenerated 27-10-2016
     */
    public $ip;

    /**
     * Url страницы которую посетили
     * 
     * @var String
     * @autogenerated 27-10-2016
     */
    public $url;

    /**
     * Время посещения страницы
     * 
     * @sqltype DATETIME
     * @var String
     * @autogenerated 27-10-2016
     */
    public $visitDate;

    public function __construct($scenario = 'insert')
    {
        $this->visitDate = DateTimeHelper::timestampToMysqlDateTime();
        parent::__construct($scenario);
    }
    
    /**
     *  Возвращает правила валидации.
     * <b>Внимание: для полей у которых в БД тип VARCHAR необходимо создать валидатор "length".</b>
     * 
     * @autogenerated 27-10-2016
     * @return Array[] Массив правил валидации
     */
    public function rules()
    {
        $arr = parent::rules();
        $arr[] = array('ip, url, visitDate','required');
        $arr[] = array('ip, url, visitDate','safe');
        $arr[] = array('visitDate','type','type' => 'datetime','datetimeFormat' => 'yyyy-MM-dd hh:mm:ss');
        return $arr;
    }
    
    /**
     * Возвращает массив связей моделей.
     * <b>Внимание: связи BELONGS_TO являются внешними ключами.</b> Для них можно указать поведение при удалений родительской сущности.
     * 
     * @autogenerated 27-10-2016
     * @return Array[] Массив связей
     */
    public function relations()
    {
        $arr = parent::relations();
        return $arr;
    }
    
    /**
     * Возвращает информацию о том, как называются поля на человеческом языке.
     * 
     * @autogenerated 27-10-2016
     * @return String[] Массив лейблов для полей (name=>label)
     */
    public function attributeLabels()
    {
        $arr = parent::attributeLabels();
        $arr["id"] = "Id";
        $arr["ip"] = "Ip";
        $arr["url"] = "Url";
        $arr["visitDate"] = "Visit date";
        return $arr;
    }
    
    /**
     * Возвращает новую модель данного класса. 
     * Этот метод необязателен, но улучшает работу подсказок.
     * 
     * @autogenerated 27-10-2016
     * @param String $className Имя класса модели
     * @return Statistics пустой объект модели
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }
    
    /**
     * Получение имени таблицы в базе данных
     *
     * @autogenerated 27-10-2016
     * @return String Название таблицы
     */
    public function tableName()
    {
        return 'accesslog';
    }  
 
}